### ISSUE TITLE
Randomized_On Date

### ISSUE THREAD

**Issue by reiniervlinschoten** [castoredc/castoRedc#11]
Hi,

When retrieving studydata, with getStudyData the following extra variables are returned:
"Record_ID", "Institute_Abbreviation", "Randomization_Group", "Record_Creation"

Would it also be possible to return the date which belongs to “Randomized_On” as this is often an important variable in randomized trials and is not captured in another way.

**Comment by aghaynes** [comment]
this is something that has just been added apparently...

**Comment by reiniervlinschoten** [comment]
Will be fixed in v2.0.0
