### ISSUE TITLE
getSurveyPackageInstances returns NULL

### ISSUE THREAD

**Issue by ArnoKalkman** [castoredc/castoRedc#13]
The function getSurveyPackageInstances returns NULL, and this appears to be a bug.

To fix this, I think CastorData.R line 92 should be:
`private$mergePages(surveypackageinstances_pages, "surveypackageinstance")`
instead of
`private$mergePages(surveypackageinstances_pages, "surveypackageinstances")`

I have tested this change locally and it seems to fix the issue.

**Comment by slknijnenburg** [comment]
Fixed in 2.0.0 via #36.
