### ISSUE TITLE
Duplicate rows in repeating data

### ISSUE THREAD

**Issue by Sofietb-work** [castoredc/castoRedc#21]
If different fields in a repeating data instance have different "created_on" times (i.e. after large imports), the getReportInstances function will create duplicate reports for each "created_on" time present.

**Comment by reiniervlinschoten** [comment]
Apologies for the late reply. The duplication issue was due to a wrong join statement (see #25).
This will be fixed in [v2.0.0](https://github.com/castoredc/castoRedc/tree/v2.0.0)
