### ISSUE TITLE
Update deprecated endpoints and parameters to newer versions

### ISSUE THREAD

**Issue by martijnkersloot** [castoredc/castoRedc#26]
In the past years, quite a lot of API endpoints have been deprecated and replaced by newer versions. In addition, some parameters for the endpoints have been marked as deprecated as well. We should make sure that the R package is updated to reflect the newer endpoints and parameters.

**Endpoints**
- `/api/study/:study_id/site[/:site_id]` replaces `/api/study/:study_id/institute[/:institute_id]`
- `/api/study/:study_id/participant[/:participant_id]` replaces `/api/study/:study_id/record[/:record_id]`
- `/api/study/:study_id/participant/:participant_id/device-token` replaces `/api/study/:study_id/record/:record_id/device-token`
- `/api/study/:study_id/participant-progress/forms` replaces `/api/study/:study_id/record-progress/steps`
- `/api/study/:study_id/visit[/:visit_id]` replaces `/api/study/:study_id/phase[/:phase_id]`
- `/api/study/:study_id/repeating-data[/:repeating_data_id]` replaces `/api/study/:study_id/report[/:report_id]`
- `/api/study/:study_id[/participant/:participant_id]/repeating-data-instance[/:repeating_data_instance_id]` replaces `/api/study/:study_id[/record/:record_id]/report-instance[/:report_instance_id]`
- `/api/study/:study_id/participant/:participant_id/repeating-data-data-point/:repeating_data_instance_id[/:field_id]` replaces `/api/study/:study_id/record/:record_id/report-data-point/:r_instance_id[/:field_id]`
- `/api/study/:study_id/repeating-data/:repeating_data_id/repeating-data-form[/:repeating_data_form_id]` replaces `/api/study/:study_id/report/:report_id/report-step[/:report_step_id]`
- `/api/study/:study_id/participant/:participant_id/randomization` replaces '/api/study/:study_id/record/:record_id/randomization`
- `/api/study/:study_id/participant/:participant_id/repeating-data-instance-collection` replaces `/api/study/:study_id/record/:record_id/report-instance-collection`
- `/api/study/:study_id/participant/:participant_id/study-data-point[/:field_id]` replaces `/api/study/:study_id/record/:record_id/study-data-point[/:field_id]`
- `/api/study/:study_id/participant/:participant_id/data-point/survey/:s_instance_id[/:field_id]` replaces `/api/study/:study_id/record/:record_id/survey-data-point/:s_instance_id[/:field_id]`
- `/api/study/:study_id[/participant/:participant_id]/data-points/:discriminator[/:identifier_id]` replaces `/api/study/:study_id[/record/:record_id]/data-point-collection/:discriminator[/:identifier_id]`
- `/api/study/:study_id[/participant/:participant_id]/survey-package-instance[/:survey_package_instance_id]` replaces `/api/study/:study_id[/record/:record_id]/surveypackageinstance[/:survey_package_instance_id]`
- `/api/study/:study_id/form[/:form_id]` replaces `/api/study/:study_id/step[/:step_id]`
- `/api/study/:study_id/survey/:survey_id/survey-form[/:survey_form_id]` replaces `/api/study/:study_id/survey/:survey_id/survey-step[/:survey_step_id]`

**Parameters**
- `/study/{study_id}/survey-package-instance`: `auto_send` field to be deprecated in favor of `available_from` in 2023.3.
- Deprecated `field_slider_step` field on endpoints `/study/:study_id/field` and `/study/:study_id/field/:field_id`. Please use `field_slider_step_value` instead.
- `/study/{study_id}/participant`. `status` property has been deprecated

**Comment by reiniervlinschoten** [comment]
Is fixed in [v2.0.0](https://github.com/castoredc/castoRedc/tree/v2.0.0)
