### ISSUE TITLE
Empty repeating data instances and survey instances

### ISSUE THREAD

**Issue by reiniervlinschoten** [castoredc/castoRedc#34]
@martijnkersloot, when exporting survey and repeating data instances, for example through getStudyData, empty surveys and repeating data instances are not retrieved.

This is an issue, as empty surveys/repeating data instances could indicate missing data.

This was also an issue in the endpoint [export data](https://data.castoredc.com/api#/export/get_study__study_id__export_data) but this was fixed in a release somewhere last year where the parameters exclude_empty_surveys and exclude_empty_reports were added.

Would it be possible to also add the empty surveys and repeating data instances to these endpoints:
- https://data.castoredc.com/api#/data-points/get_study__study_id__data_points_survey_instance
- https://data.castoredc.com/api#/data-points/get_study__study_id__data_points_repeating_data_instance

But preferably  to all data_points endpoints that return repeating data or survey instances?

**Comment by martijnkersloot** [comment]
👋 These endpoints do not return empty surveys on purpose, as there are no data points collected and thus none to return. Is there a way for you to leverage the `/study/{study_id}/export/data` endpoint instead or to combine the results of the `data-points` endpoints with the repeating data / survey structure from the `repeating-data-instance` and `survey-instance` endpoints?

**Comment by reiniervlinschoten** [comment]
> 👋 These endpoints do not return empty surveys on purpose, as there are no data points collected and thus none to return. Is there a way for you to leverage the `/study/{study_id}/export/data` endpoint instead or to combine the results of the `data-points` endpoints with the repeating data / survey structure from the `repeating-data-instance` and `survey-instance` endpoints?

I will check!

**Comment by martijnkersloot** [comment]
Fixed in #40
