### ISSUE TITLE
Minimum version of {purrr} is not documented in DESCRIPTION

### ISSUE THREAD

**Issue by lcreteig** [castoredc/castoRedc#44]
The package makes use of `purrr::discard_at()`, which was introduced relatively late in [v1.0.0](https://www.tidyverse.org/blog/2022/12/purrr-1-0-0/#keep_at-and-discard_at). I was still running an older version and therefore got an error while retrieving my study data.

**Comment by reiniervlinschoten** [comment]
Fixed in #50
