### ISSUE TITLE
All values in checkbox columns are `FALSE`

### ISSUE THREAD

**Issue by lcreteig** [castoredc/castoRedc#46]
First off, thanks a lot for all the improvements in the v2.0 release; I feel like the package is much more user-friendly now!

The only problem I've encountered is that columns based on checkbox fields in the study data frame returned by `getStudyData()` have the value `FALSE` for every participant, regardless of whether these checkboxes have actually been ticked in Castor.

I was able to trace the source of the problem and will propose a PR shortly (of course, if that's not appreciated, feel free to disregard it, but in my opinion the issue does warrant a fix).

**Comment by reiniervlinschoten** [comment]
Fixed in #50
