### ISSUE TITLE
API secret longevity

### ISSUE THREAD

**Issue by aghaynes** [castoredc/castoRedc#9]
I might have use for your package very soon (days to weeks)...

How long does the secret last? I saw on the link in the readme that they only last for 5 hours...? That might make it a pain for working with (always having to generate a secret, ...)

Thanks!

**Comment by martijnkersloot** [comment]
Hi Alan, 

I'm so sorry that we're only getting back to you now. Hopefully, you've been able to use our R package in the meantime :).

The Client ID and secret can be [generated from the "User Settings" page](https://helpdesk.castoredc.com/link-castor-to-another-application/application-programming-interface-api), and they won't expire unless you choose to regenerate them from the same page. The OAuth Access Token has a 5-hour expiration period and will be requested automatically when you run `CastorData$new`.

Best regards,
Martijn (Product Owner, Castor CDMS)
